@startuml 
|Customer|
start
:Order carport online;
|#AntiqueWhite|Sales Representative|
:Data Entry;
if(Data validation)  then (True)
:Contact customer;
|Customer|
:Reevaluate carport order;
else(False) 
endif
|Sales Representative|
:Estiamte final offer;
|Customer|
:Accept order;
|Sales representative|
:Finish and prepare order;
|Logistics Worker|
:Read Bill of Materials and prepare order;
:Ship order;
|Customer|
:Recieve goods;
:Construct Carport;
stop
@enduml