@startuml
|Sales Representative|
:Enter user information (Name and password);
|#AntiqueWhite|IT-system|
:Request user;
|Data-Base|
:Search for user;
|IT-system|
:Password check;
:Complete login;
:Request user orders;
|Data-Base|
:Find active and open cases;
|IT-system|
:Show cases to user;
|Sales Representative|
:Open and resolve cases & contact customer;
end
@enduml