@startuml
|Sælger|
:Indtast Bruger information (Navn og Password);
|#AntiqueWhite|IT-system|
:Find bruger;
|Data-Base|
:Søg efter bruger;
|IT-system|
:Vurder om Kodeord er korrekt;
:gennemfør logind;
:Request brugerens sager;
|Data-Base|
:Find aktive sager og åbne sager;
|IT-system|
:Presenter sager for brugeren;
|Sælger|
:Åben og resolve cases skrive til kunder;
end
@enduml